### PR TITLE
WIP: follow mouse in a lazy manner - only when it moves out of the frame

### PR DESCRIPTION
**Pull request by koo5**
hi.

seems to work on my machine. 

would there be interest in merging this functionality if i add a new command line option for it? (--follow-mouse-lazy?)

### CODE REVIEW

**Comment by Enselic** [comment]
Hi, and thanks for taking the time to make a WIP-contribution.

This project is currently in a bit of a mid-air state, and it is not obvious where to make contributions.

The 0.4.0 release I made some months back has made its way into both [Ubuntu](https://packages.ubuntu.com/hirsute/recordmydesktop) and [Debian unstable](https://packages.debian.org/unstable/video/recordmydesktop). So far so good.

However, the current Debian maintainer (who is on GitHub, but I don't want to @ him, because he does not like that) has requested/demanded that the work of @vcaputo (see https://github.com/recordmydesktop/recordmydesktop) is included in the next official release.

Me, @vcaputo, and the Debian maintainer is having an email conversation about the future of the project. Before all open questions have been resolved, I don't consider it feasible to make a new release, since I (at least currently) find it important to be included in Debian.

The Debian maintainer is a busy guy, and `recordMyDesktop` is not a prioritized project for him. So it will take many months, possibly years, before we have resolved all open questions.

If I _had_ to give a recommendation, it would be to contribute to https://github.com/recordmydesktop/recordmydesktop instead. Because that currently seems like the most likely base for the next release. Not sure if @vcaputo agrees though.

**Comment by vcaputo** [comment]
Feature sounds reasonable, honestly I'm not sure `--follow-mouse` even works at all currently @ https://github.com/recordmydesktop/recordmydesktop  as I've never used the feature.  @koo5 I'd be open to landing something in this vein, but fully expect a `--follow-mouse` bugfix to likely be required first.  If you're up for peeking down in that rabbithole I can make some time for reviewing/testing relevant PRs.

**Comment by koo5** [comment]
@vcaputo i tested your version and you're right that `--follow-mouse` doesn't work. Unfortunately, none of this is a priority for me.

**Comment by vcaputo** [comment]
@koo5 I took a few mins to investigate the breakage and have pushed a fix.

If you're actually using this for something, I suspect you'll find the fork @ https://github.com/recordmydesktop/recordmydesktop generally works better.

Adding a "lazy" `--follow-mouse` variant has now been added to my personal rmd todo list, but no guarantees on when I can get around to that.  If you're interested in adding it, at least the base functionality is working again now.

**Comment by Enselic** [comment]
Let's close this, since the readme now recommends to direct contributions towards recordmydesktop/recordmydesktop.

**Pull request closed without merging**
